const mercenaries = [
  {
    id: 1,
    name: "Neo",
    lvl: 2,
    price: 3500,
    strength: 37,
    hired: false,
    planet: "therion",
  },
  {
    id: 2,
    name: "Jin",
    lvl: 3,
    price: 5500,
    strength: 60,
    hired: false,
    planet: "therion",
  },
  {
    id: 3,
    name: "Shrimp",
    lvl: 4,
    price: 7500,
    strength: 82,
    hired: false,
    planet: "therion",
  },
  {
    id: 4,
    name: "Lucy",
    lvl: 4,
    price: 8500,
    strength: 95,
    hired: false,
    planet: "therion",
  },
  {
    id: 5,
    name: "Rusty",
    lvl: 5,
    price: 9500,
    strength: 105,
    hired: false,
    planet: "therion",
  },
  {
    id: 6,
    name: "Alpha",
    lvl: 4,
    price: 8500,
    strength: 98,
    hired: false,
    planet: "crystalia",
  },
  {
    id: 7,
    name: "Hammer",
    lvl: 6,
    price: 12500,
    strength: 130,
    hired: false,
    planet: "crystalia",
  },
  {
    id: 8,
    name: "Prototype",
    lvl: 7,
    price: 11000,
    strength: 115,
    hired: false,
    planet: "crystalia",
  },
  {
    id: 9,
    name: "Dot",
    lvl: 7,
    price: 12500,
    strength: 140,
    hired: false,
    planet: "crystalia",
  },
  {
    id: 10,
    name: "Scythe",
    lvl: 5,
    price: 10500,
    strength: 110,
    hired: false,
    planet: "bathea",
  },
  {
    id: 11,
    name: "Brainstorm",
    lvl: 5,
    price: 9500,
    strength: 96,
    hired: false,
    planet: "bathea",
  },
  {
    id: 12,
    name: "Ranger",
    lvl: 8,
    price: 16500,
    strength: 180,
    hired: false,
    planet: "bathea",
  },
];

export default mercenaries;
